#!/bin/bash
source .env

echo "Source Dir: $source_dir"
echo "Target Dir: $target_dir"
echo "Source Folder: $source_folder"
echo "Target Folder: $target_folder"

echo ""
echo "Source path: $source_dir/$source_folder"
echo "Target path: $target_dir/$target_folder"
echo "--------------------------------"
echo ""
date

times=""

echo "process^real^user^sys"
for i in `seq 1 $instance_count`;
        do
	input="$target_dir/commit$i.time"
#	echo "File commit$i.time"

	while IFS= read -r var
	do
        	if [ -n "$var" ]; then
#                	echo "$var"
			tokens=( $var )
			if [ -n "$times" ]; then
				times=$times^${tokens[1]}
			else
				times=commit$i.time^${tokens[1]}
			fi
        	fi
	done < "$input" 
	echo -e $times
	times=""
done
