#!/bin/bash

source .env

echo "Source Dir: $source_dir"
echo "Target Dir: $target_dir"
echo "Source Folder: $source_folder"
echo "Target Folder: $target_folder"

echo ""
echo "Source path: $source_dir/$source_folder"
echo "Target path: $target_dir/$target_folder"
echo "--------------------------------"
echo ""
date

for i in `seq 1 $instance_count`;
        do
                echo "creating test project $target_folder$i"
               cp -R $source_dir/$source_folder $target_dir/$target_folder$i
        done

exit 0
~

